### PR TITLE
Use Azure to build Windows pks

### PR DESCRIPTION
**Pull request by ocefpaf**
Not sure why we had this pinned to AppVeyor.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Things works OK on AppVeyor but fails on Azure. @isuruf this one does not use `cmake` but relies on `flang` to build the Windows Fortran extension. Do you have any advice for us?

PS: this is part of the effort to move from AppVeyor to Azure so we can implement CFEP-13.

**Comment by isuruf** [comment]
Are you sure this works on appveyor? Can you try a new build with appveyor?

**Comment by ocefpaf** [comment]
> Are you sure this works on appveyor? Can you try a new build with appveyor?

Yep. It is passing: https://ci.appveyor.com/project/conda-forge/climlab-feedstock/builds/31560633/job/7sgbkyaoevk97thd

**Comment by brian-rose** [comment]
Hi, I've had this pinned to Appveyor for quite a while because I never succeeded in getting the Windows build working on azure. It would be great to fix this but I've never quite known where to begin.

**Comment by ocefpaf** [comment]
Wow! Thanks @isuruf!! I'll clean up the AppVeyor stuff later so we can merge this.

**Comment by brian-rose** [comment]
Excellent, thanks @isuruf and @ocefpaf !

**Pull request merged**
