### PR TITLE
Experimental multi-platform build of climlab v0.6.3.dev4 

### PR DESCRIPTION
**Pull request by brian-rose**
- Uses flang to build for win/py3k
- Updates to the climlab codebase should fix some of the other recent build problems

### CODE REVIEW

**Comment by brian-rose** [comment]
@conda-forge-admin, please rerender

**Comment by brian-rose** [comment]
@conda-forge-admin, please rerender

**Comment by brian-rose** [comment]
@conda-forge-admin, please rerender

**Comment by ghost** [comment]
cc @isuruf. Why is 32-bit py2k skipped?

**Comment by brian-rose** [comment]
Also if anyone has any insight into why win64/py2k is failing, I'd love to hear it. As far as I can see, that part of the recipe has not changed.

appveyor logs keep showing a failure during link stage of the fortran build:

```
error: Command "link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\bld\climlab_1518647748056\_b_env\share\mingwpy\lib\gcc\x86_64-w64-mingw32\4.9.2 /LIBPATH:C:\bld\climlab_1518647748056\_b_env\libs /LIBPATH:C:\bld\climlab_1518647748056\_b_env\PCbuild\amd64 /LIBPATH:C:\bld\climlab_1518647748056\_b_env\PC\VS9.0\amd64 /LIBPATH:C:\bld\climlab_1518647748056\_b_env\libs /LIBPATH:C:\bld\climlab_1518647748056\_b_env\PCbuild\amd64 /LIBPATH:C:\bld\climlab_1518647748056\_b_env\PC\VS9.0\amd64 /EXPORT:init_emanuel_convection build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\climlab\convection\_emanuel_convection\_emanuel_convectionmodule.obj build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\fortranobject.obj build\temp.win-amd64-2.7\Release\climlab\convection\_emanuel_convection\convect.o build\temp.win-amd64-2.7\Release\climlab\convection\_emanuel_convection\Driver.o /OUT:build\lib.win-amd64-2.7\climlab\convection\_emanuel_convection\_emanuel_convection.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\climlab\convection\_emanuel_convection\_emanuel_convection.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\climlab\convection\_emanuel_convection\_emanuel_convection.pyd.manifest" failed with exit status 1120
```

**Comment by brian-rose** [comment]
@conda-forge-admin, please rerender

**Comment by brian-rose** [comment]
Finally got py35 and py36 passing on all platforms. I’m going to release the source as climlab v0.6.3 and update the recipe one more time. 

Abandoning win/py27 for now.

**Pull request closed without merging**
