### PR TITLE
Add win/py3k build

### PR DESCRIPTION
**Pull request by ghost**
Closes gh-7.

### CODE REVIEW

**Comment by ghost** [comment]
@conda-forge-admin Please rerender.

**Comment by ghost** [comment]
@conda-forge-admin Please rerender.

**Comment by ghost** [comment]
@brian-rose You need to use flang to build for Python 3, and I haven't and don't plan to add 32 bit support. However, py36/x64 is built here, and despite the failures for py27/x64, there's already an existing build.

**Comment by brian-rose** [comment]
@xoviat Ok! Thanks so much for these pointers. I was not aware of flang. I'll work on fine-tuning the recipe. py36/x64 is probably the highest priority anyway.

**Pull request closed without merging**
